{% set name = "xagg" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xagg-{{ version }}.tar.gz
  sha256: b4ea7e975939187e1486e1260cb428c3182f384eb74a194a2041c6a763ef1898

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - cf_xarray >=0.5.1
    - esmpy >=8.1.0
    - geopandas
    - netcdf4
    - numpy
    - pandas
    - python >=3.6
    - requests
    - scipy
    - shapely
    - xarray
    - xesmf >=0.5.2
    - numba

test:
  imports:
    - xagg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ks905383/xagg
  summary: Aggregating raster data over polygons
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ks905383
    - raybellwaves
