{% set name = "xagg" %}
{% set version = "0.3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xagg-{{ version }}.tar.gz
  sha256: 5679ec250a91751fc06bb808cee62c4751850004c54123c56f3db82f5c8eb7e2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools-scm
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - xarray
    - pandas
    - netcdf4
    - geopandas
    - shapely
    - pytables
    - xesmf >=0.5.2
    - cf_xarray >=0.7.1
    - esmpy >=8.1.0
    - requests

test:
  imports:
    - xagg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ks905383/xagg
  summary: Aggregating raster data over polygons
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ks905383
