{% set name = "xagg" %}
{% set version = "0.2.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xagg-{{ version }}.tar.gz
  sha256: b81d54c71d9a92a4834f77668aec17e6dfb5eac4c61850cb70f4579bbf7df266

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - cf_xarray >=0.5.1
    - esmpy >=8.1.0
    - geopandas
    - netcdf4
    - numpy
    - pandas
    - requests
    - scipy
    - shapely
    - xarray
    - xesmf >=0.5.2

test:
  imports:
    - xagg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ks905383/xagg
  summary: Aggregating raster data over polygons
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ks905383
    - raybellwaves
